# 采购订单系统配置文件

# 服务器配置
server:
  port: "8080"                    # 服务端口
  read_timeout: 60                # 读取超时时间（秒）
  write_timeout: 60               # 写入超时时间（秒）

# 数据库配置
database:
  type: "sqlite"                  # 数据库类型: sqlite, postgres, mysql
  file_path: "./purches.db"       # SQLite数据库文件路径
  host: "localhost"               # 数据库主机（非SQLite时使用）
  port: 5432                      # 数据库端口（非SQLite时使用）
  name: "purches"                 # 数据库名（非SQLite时使用）
  user: ""                        # 数据库用户名（非SQLite时使用）
  password: ""                    # 数据库密码（非SQLite时使用）
  ssl_mode: "disable"             # SSL模式（PostgreSQL）

# 应用配置
app:
  name: "采购订单系统"
  version: "1.0.0"
  environment: "development"       # development, production, testing
  log_level: "info"               # debug, info, warn, error
  default_user_id: "user_1"       # 默认用户ID（简化版本） 